#%RAML 1.0 DataType
properties: 
  id: number
  title: string
  author: string
  ISBN: number
  genre: string
examples:
  one:
    id: 1
    title: API Design
    author: Mr Writer
    ISBN: 263918239890812 
    genre: IT
  two:
    id: 2
    title: Elon Musk Biography
    author: John Author
    ISBN: 312378732189732
    genre: Bio